/* Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add 
 * one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */
#include <iostream>
#include <string>
#include <vector>
#include <unordered_set>
#include <unordered_map>
#include <algorithm>
#include <stack>
#include <queue>
#include <list>
#include <set>
using namespace std;

class Solution {
public:
	char findTheDifference(string s, string t) {
		int arrs[26] = { 0 }, arrt[26] = { 0 };
		auto sz = s.size();
		for (decltype(sz) i = 0; i < sz; ++i) {
			++arrs[s[i] - 'a'];
			++arrt[t[i] - 'a'];
		}
		++arrt[t[sz] - 'a'];
		for (int i = 0; i < 26; ++i) {
			if (arrs[i] != arrt[i])
				return 'a' + i;
		}
		return 'a';
	}
};

int main()
{
	Solution s = Solution();
	
	cout << (char)('a'^'b'^'a');
	system("pause");
	return 0;
}